name: "Hello World!"

on: workflow_dispatch

jobs:
    say_hello_in_bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "i am running in the bash of ubuntu"
jobs:
    make-dir-happy:
        runs-on: ubuntu-18.04
        steps:
            - name: make a directory
              run: mkdir -p ~/happy/is/best/doing
            - name: show the config of current running os
              run: uname -a
